CREATE TABLE IF NOT EXISTS REGISTRATION (id INTEGER not NULL, first VARCHAR(255), last VARCHAR(255), age INTEGER, PRIMARY KEY ( id ))
# neue Tabellen
CREATE TABLE IF NOT EXISTS ITEM (id INTEGER not NULL, name VARCHAR(255), PRIMARY KEY ( id ))
CREATE TABLE IF NOT EXISTS MONSTER (id INTEGER not NULL, name VARCHAR(255), PRIMARY KEY ( id ))