INSERT INTO Skill (name) VALUES ('Short blade')
INSERT INTO Skill (name) VALUES ('Long blade')
INSERT INTO Skill (name) VALUES ('Bite')
INSERT INTO Skill (name) VALUES ('Sting')

INSERT INTO Skill (name) VALUES ('Sneaking')
INSERT INTO Skill (name) VALUES ('Alchemy')
INSERT INTO Skill (name) VALUES ('Tracking')
INSERT INTO Skill (name) VALUES ('Climbing')
INSERT INTO Skill (name) VALUES ('Acrobatics')
INSERT INTO Skill (name) VALUES ('Swimming')