INSERT INTO Equipmentslottype (name) VALUES ('Any hand');
INSERT INTO Equipmentslottype (name) VALUES ('Primary hand');
INSERT INTO Equipmentslottype (name) VALUES ('Secondary hand');
INSERT INTO Equipmentslottype (name) VALUES ('Twohanded');
INSERT INTO Equipmentslottype (name) VALUES ('Off hand');
INSERT INTO Equipmentslottype (name) VALUES ('Body');
INSERT INTO Equipmentslottype (name) VALUES ('Legs');
INSERT INTO Equipmentslottype (name) VALUES ('Feet');
INSERT INTO Equipmentslottype (name) VALUES ('Head');
INSERT INTO Equipmentslottype (name) VALUES ('Jaws');
INSERT INTO Equipmentslottype (name) VALUES ('Abdomen');
